const SET_SELECTED_COUNTRY = "SET_SELECTED_COUNTRY";
const SEND_MESSAGE = "SEND_MESSAGE";
const SET_COUNTRIES = "SET_COUNTRIES";
const SET_GRAPH_DATA = "SET_GRAPH_DATA";
const TOGGLE_GRPAH_DIALOG = "TOGGLE_GRPAH_DIALOG";
const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
const RESET_SEARCH_RESULTS = "RESET_SEARCH_RESULTS";


export {
  SET_SELECTED_COUNTRY,
  SEND_MESSAGE,
  SET_COUNTRIES,
  SET_GRAPH_DATA,
  TOGGLE_GRPAH_DIALOG,
  SET_SEARCH_RESULTS,
  RESET_SEARCH_RESULTS,
};
